FROM maven:3.8.6-jdk-17-slim AS build
WORKDIR /app
COPY pom.xml .
COPY src src
RUN mvn clean package

FROM openjdk:11.0.11-jre-slim
ARG JAR_FILE=hello-world-0.0.1-SNAPSHOT.jar
COPY --from=build /app/target/${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]