FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src src
RUN mvn clean package

FROM openjdk:11.0.11-jre-slim
ARG JAR_FILE=hello-world.jar
COPY --from=build /app/target/${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]